export const SET_INGREDIENTS_DATA = "INGREDIENTS_DATA";
export const SET_CONSTRUCTOR_DATA = "CONSTRUCTOR_DATA";

export const GET_FEED_SUCCESS = "GET_FEED_SUCCESS";
export const GET_FEED_FAILED = "GET_FEED_FAILED";
export const SET_ORDER = "SET_ORDER";
export const SET_CART_OF_ITEM_ID = "SET_CART_OF_ITEM_ID";