export const GET_INGREDIENTS_REQUEST = "GET_INGREDIENTS_REQUEST";
export const GET_INGREDIENTS_SUCCESS = "GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENTS_ERROR = "GET_INGREDIENTS_ERROR";

export const POST_ORDER_REQUEST = "POST_ORDER_REQUEST";
export const POST_ORDER_SUCCESS = "POST_ORDER_SUCCESS";
export const POST_ORDER_ERROR = "POST_ORDER_ERROR";

export const SET_ORDER = "SET_ORDER";

export const ADD_CONTAINER_ITEM = "ADD_CONTAINER_ITEM";
export const SET_CONTAINER_BUN = "SET_CONTAINER_BUN";
export const REMOVE_CONTAINER_ITEM = "REMOVE_CONTAINER_ITEM";
export const REPLACE_CART_INGREDIENTS = "REPLACE_CART_INGREDIENTS";
export const MOVE_CART_ITEM_TO_INDEX = "MOVE_CART_ITEM_TO_INDEX";