export const REQUEST_IS_READY: "REQUEST_IS_READY" = "REQUEST_IS_READY";
export const SET_MODAL_INVISIBLE: "SET_MODAL_INVISIBLE" = "SET_MODAL_INVISIBLE";

export const OPEN_INGREDIENT_MODAL: "OPEN_INGREDIENT_MODAL" = "OPEN_INGREDIENT_MODAL";
export const OPEN_ORDER_MODAL: "OPEN_ORDER_MODAL" = "OPEN_ORDER_MODAL";
